Information about loading data into the Bridgehead's FHIR store
samply/bridgehead pull request #130
Opened 2023-10-20 08:29 UTC by DavidCroftDKFZ

Added this information because many sites have asked about it.

2023-10-31 09:51 UTC, patrickskowronekdkfz requested changes

2023-10-31 09:51 UTC, patrickskowronekdkfz commented on README.md
> +https://<Name of your server>/bbmri-localdatamanagement/fhir
Please replace the BBMRI with project.

2023-10-31 09:51 UTC, patrickskowronekdkfz commented on README.md
> +The FHIR API uses basic auth. You can find the credentials in `/etc/bridgehead/bbmri.local.conf`.
Please replace BBMRI with the project.

2023-10-31 09:51 UTC, patrickskowronekdkfz commented on README.md
> +- If you are a German biobank and you already feed your data into a Data Integration Center (DIZ). In this case, you can use the [TransFAIR tool](https://github.com/samply/transFAIR) with the `bbmri2
Currently still in development, I would add it, when it is ready.

2023-11-08 08:48 UTC, DavidCroftDKFZ commented on README.md
> +https://<Name of your server>/bbmri-localdatamanagement/fhir
Done

2023-11-08 09:26 UTC, patrickskowronekdkfz approved these changes

2023-11-21 10:10 UTC, merged