refactor: optimize memory usage of blaze
samply/bridgehead pull request #154
Opened 2024-02-20 14:20 UTC by torbrenner

2024-02-20 15:56 UTC, TKussel requested changes

2024-02-20 15:56 UTC, TKussel commented on lib/functions.sh
> +	   system_memory_in_mb=$(("$system_memory"/1024));
Depending on the /proc file system is always a bit tricky and potentially not portable. How about the following:
```suggestion
	   system_memory_in_mb=$(free -m | grep 'Mem:' | awk '{print $2}');
```

2024-02-20 15:56 UTC, TKussel commented on bbmri/docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-Xmx${BLAZE_MEMORY_CAP}m"
Maybe add a 4g limit as a default value?
```suggestion
      JAVA_TOOL_OPTIONS: "-Xmx${BLAZE_MEMORY_CAP:-4096}m"
```

2024-02-21 07:39 UTC, patrickskowronekdkfz commented
Since we only set JAVA Heap and not the DB_BLOCK_CACHE_SIZE, your example might be faster in certain cases then with only 4GB of JAVA Heap. Maybe we should test this as well.

Anyways, Maybe it makes also sense to inform the User that the available RAM is not enough to have good performance.

2024-02-23 07:32 UTC, torbrenner commented on bbmri/docker-compose.yml
> -      LOG_LEVEL: "debug"
Yes, i don't think we should use debug log level on production sites. As far as i know in the initial configuration we activated debug unintentional and removed it later for ccp.
But to be sure, we should discuss this change first.

2024-03-05 09:48 UTC, patrickskowronekdkfz requested changes
We would need to set DB_RESOURCE_CACHE_SIZE, according to https://github.com/samply/blaze/blob/master/docs/tuning-guide.md, however this would imply a default value which could make the performance worse.

2024-03-05 09:48 UTC, patrickskowronekdkfz commented on bbmri/docker-compose.yml
> +      DB_BLOCK_CACHE_SIZE: $BLAZE_MEMORY_CAP
DB_RESOURCE_CACHE_SIZE is missing which is also an important Value. We would need for 2500000 for 4GB RAM. However this value depends on the physical size of data and the amount of resources.

2024-03-11 09:32 UTC, patrickskowronekdkfz approved these changes
I think now everything in it should work, we should test it at site and compare the performance.

2024-03-15 08:55 UTC, merged