Added a Directory sync component
samply/bridgehead pull request #53
Opened 2023-01-27 12:53 UTC by DavidCroftDKFZ

* Added new container to bbmri/docker-compose.yml.
* Added set up documentation to README.

2023-02-23 13:54 UTC, patrickskowronekdkfz requested changes

2023-02-23 13:54 UTC, patrickskowronekdkfz commented on bbmri/docker-compose.yml
> +      DS_FHIR_STORE_URL: "http://bridgehead-bbmri-blaze:8080"
Should be default in the spring application.yml

2023-02-23 13:54 UTC, patrickskowronekdkfz commented on bbmri/docker-compose.yml
> +      DS_RETRY_MAX: ${DS_RETRY_MAX}
Should be default in the spring application.yml

2023-02-23 13:54 UTC, patrickskowronekdkfz commented on bbmri/docker-compose.yml
> +      DS_RETRY_INTERVAL: ${DS_RETRY_INTERVAL}
Should be default in the spring application.yml

2023-02-23 13:54 UTC, patrickskowronekdkfz commented on README.md
> +This is an optional feature for bbmri projects.  It keeps the [BBMRI Directory](https://directory.bbmri-eric.eu/) up to date with the number of samples, etc.  kept in your biobank. It also updates th
```suggestion
This is an optional feature for bbmri projects. It keeps the [BBMRI Directory](https://directory.bbmri-eric.eu/) up to date with your local data eg. number of samples. It also updates the local FHIR store with the latest contact details etc. from the Directory.  You must explicitly set your country specific directory url, username and password to enable this feature.
```

2023-02-23 13:54 UTC, patrickskowronekdkfz commented on README.md
> +To enable it, you will need to add some extra variables to the ```bbmri.conf``` file in your GitLab repository, for example:
```suggestion
To enable it, you will need to set these variables in the ```bbmri.conf``` file of your GitLab repository. Here is an example config:
```

2023-02-23 13:54 UTC, patrickskowronekdkfz commented on README.md
> +Additionally, you should choose when you want Directory sync to run. In the example above, this is set to happen at 10 pm every evening. You can modify this to suit your requirements. The timer speci
```suggestion
Additionally, you should choose when you want Directory sync to run. In the example above, this is set to happen at 10 pm every evening. You can modify this to suit your requirements. The timer specification should follow the [cron](https://crontab.guru) convention
```

2023-02-23 13:54 UTC, patrickskowronekdkfz commented on README.md
> +Once you have made the changes, update your local configuration:
```suggestion
Once you edited the gitlab config. The bridgehead will autoupdate the config with the values and will sync the data.
```

2023-02-23 13:54 UTC, patrickskowronekdkfz commented on README.md
> +```
Not needed

2023-02-23 13:57 UTC, patrickskowronekdkfz commented
- [ ] TODO: add these values to the template and each repo

2023-03-31 06:05 UTC, patrickskowronekdkfz approved these changes
Needs a second reviewer

2023-03-31 06:06 UTC, patrickskowronekdkfz commented
@torbrenner please look at this PR

2023-03-31 07:15 UTC, torbrenner requested changes

2023-03-31 07:15 UTC, torbrenner commented on bbmri/directory-sync-compose.yml
> +    image: "samply/directory_sync_service"
Please use `docker.verbis.dkfz.de/cache/samply/directory_sync_service`

2023-03-31 10:18 UTC, patrickskowronekdkfz commented on bbmri/directory-sync-compose.yml
> +    image: "samply/directory_sync_service"
@torbrenner done

2023-04-03 06:36 UTC, torbrenner approved these changes

2023-04-03 06:45 UTC, merged