add custom-certs for nngm connector
samply/bridgehead pull request #63
Opened 2023-03-06 12:51 UTC by PierreDelpy

2023-03-06 15:50 UTC, torbrenner approved these changes

2023-03-08 08:39 UTC, lablans requested changes

2023-03-08 08:47 UTC, torbrenner commented on ccp/nngm-compose.yml
> +      - /etc/bridgehead/trusted-ca-certs:/custom-certs
i would agree that we dont need it writeable. Pushed a commit to make it read-only

2023-03-09 22:59 UTC, lablans approved these changes

2023-03-17 06:56 UTC, closed without merging